ALTER TABLE `patientPrescriptions`
  MODIFY COLUMN `status` enum('UNSIGNED / DEMO','SIGNED — DEMO STATE','UNSIGNED / CONTROLLED WORKSPACE','SIGNED — CONTROLLED STATE') NOT NULL DEFAULT 'UNSIGNED / DEMO';

UPDATE `patientPrescriptions`
SET `status` = CASE `status`
  WHEN 'UNSIGNED / DEMO' THEN 'UNSIGNED / CONTROLLED WORKSPACE'
  WHEN 'SIGNED — DEMO STATE' THEN 'SIGNED — CONTROLLED STATE'
  ELSE `status`
END;

ALTER TABLE `patientPrescriptions`
  MODIFY COLUMN `status` enum('UNSIGNED / CONTROLLED WORKSPACE','SIGNED — CONTROLLED STATE') NOT NULL DEFAULT 'UNSIGNED / CONTROLLED WORKSPACE';
